version: "3.2"
services:
  # 配置中心
  zsc-config:
    # 镜像地址
    image: 123.207.79.123:5000/zsc-config:0.0.1-SNAPSHOT
    # 容器名称
    container_name: zsc-config
    ports:
      # 端口映射
      - "8888:8888"
    environment:
      - PUBLIC_RABBITMQ_HOST=rabbitmq
      - PUBLIC_RABBITMQ_USERNAME=guest
      - PUBLIC_RABBITMQ_PASSWORD=guest
      - CONFIG_SERVER_SECURITY_NAME=user
      - CONFIG_SERVER_SECURITY_PASSWORD=12345678
      - CONFIG_SERVER_ENCRYPT_KEY=12345678
      - EUREKA_SERVICE_URL=http://zsc-eureka-1:8761/eureka/,http://zsc-eureka-2:8761/eureka/
      - LOGSTASH_HOST=logstash:4560
      - JAVA_OPTS=-Dspring.profiles.active=prod
    # 在eureka容器之后启动
    depends_on:
      - zsc-eureka-1
      - zsc-eureka-2
    volumes:
      # 将宿主机上的文件挂载到容器内
      - type: "bind"
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      # 实例数量
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      # 更新选项
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '0.5'
          # 内存限制
          memory: 256M