# 公共组件部署
# 基础组件eureka1、eureka2、config-server

version: "3.2"
services:
  eureka1:
    # 镜像地址
    image: 123.207.79.123:5000/zsc-eureka:0.0.1-SNAPSHOT
    # 容器名称
    container_name: eureka1
    ports:
      # 端口映射,这里单纯的是为了在外部能够访问eureka
      - "8761:8761"
    environment:
      # hostname URL
      - EUREKA_SERVICE_URL="http://eureka1:8761/eureka/,http://eureka2:8761/eureka/"
      - HOSTNAME="eureka1"
      - LOGSTASH_HOST="logstash:4560"
      - JAVA_OPTS="-Xms128m -Xmx256m -Dspring.profiles.active=prod"
    networks:
      # 加入集群网络
      - swarm_net
    volumes:
      # 将宿主机上的文件挂载到容器内
      - type: "bind"
        source: /etc/localtime
        target: /etc/localtime
    # 集群部署下需要用到的参数
    deploy:
      # 实例数量
      replicas: 1
      # 更新选项
      placement:
        constraints:
          - node.role == worker
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '0.5'
          # 内存限制
          memory: 256M
  # 2、eureka2
  eureka2:
    # 镜像地址
    image: 123.207.79.123:5000/zsc-eureka:0.0.1-SNAPSHOT
    # 容器名称
    container_name: eureka2
    ports:
      # 端口映射
      - "8762:8761"
    environment:
      # hostname
      - EUREKA_SERVICE_URL="http://eureka1:8761/eureka/,http://eureka2:8761/eureka/"
      - HOSTNAME="eureka2"
      - LOGSTASH_HOST="logstash:4560"
      - JAVA_OPTS="-Xms128m -Xmx256m -Dspring.profiles.active=prod"
    networks:
      # 加入集群网络
      - swarm_net
    volumes:
      # 将宿主机上的文件挂载到容器内
      - type: "bind"
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      # 实例数量
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      # 更新选项
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '0.5'
          # 内存限制
          memory: 256M
  # 3、配置中心
  config-server:
    # 镜像地址
    image: 123.207.79.123:5000/config-server:0.0.1-SNAPSHOT
    # 容器名称
    container_name: config-server
    ports:
      # 端口映射
      - "8888:8888"
    environment:
      - PUBLIC_RABBITMQ_HOST="rabbitmq"
      - PUBLIC_RABBITMQ_USERNAME="guest"
      - PUBLIC_RABBITMQ_PASSWORD="guest"
      - CONFIG_SERVER_SECURITY_NAME="tony"
      - CONFIG_SERVER_SECURITY_PASSWORD="12345678"
      - CONFIG_SERVER_ENCRYPT_KEY="12345678"
      - EUREKA_SERVICE_URL="http://eureka1:8761/eureka/,http://eureka2:8761/eureka/"
      - LOGSTASH_HOST="logstash:4560"
      - JAVA_OPTS="-Xms128m -Xmx256m -Dspring.profiles.active=prod"
    networks:
      # 加入集群网络
      - swarm_net
    # 在eureka容器之后启动
    depends_on:
      - eureka1
      - eureka2
    volumes:
      # 将宿主机上的文件挂载到容器内
      - type: "bind"
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      # 实例数量
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      # 更新选项
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '0.5'
          # 内存限制
          memory: 256M

networks:
  swarm_net: