# 上下文初始化加载
info:
  name: Eureka server

logstashHost: logstash:4560

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8761
eureka:
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉取信息
    fetchRegistry: false
    # eureka server地址
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
  instance:
    hostname: eureka1

---
spring:
  profiles: test
server:
  port: 8761
eureka:
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉取信息
    fetchRegistry: false
    # eureka server地址
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
  instance:
    # compose - environment HOSTNAME
    hostname: ${HOSTNAME}

---
spring:
  profiles: prod
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: true
    # 服务剔除任务执行周期
    evictionIntervalTimerInMs: 60000
    # 服务端缓存最长时间
    responseCacheUpdateIntervalMs: 30000
  instance:
    hostname: ${HOSTNAME}