info:
  name: 配置中心

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  # rabbitmq的地址 用户名 密码
  rabbitmq:
    host: www.zhangzp.cn
    username: guest
    password: guest
server:
  port: 8888
# 使得/refresh不需要验权
management:
  security:
    enabled: false
# 访问时需要提供用户和密码
security:
  basic:
    enable: true
  # 这个接口不做用户名密码校验, /monitor接收git刷新通知
  ignored: /monitor
  user:
    name: user
    password: 12345678
encrypt:
  # 加解密用的秘钥
  key: 12345678

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
    # 心跳间隔
    leaseRenewalIntervalInSeconds: 10
# logback 配置 logstash

---
spring:
  profiles: test
  # rabbitmq的地址 用户名 密码
  rabbitmq:
    host: ${PUBLIC_RABBITMQ_HOST:rabbitmq}
    username: ${PUBLIC_RABBITMQ_USERNAME:guest}
    password: ${PUBLIC_RABBITMQ_PASSWORD:guest}
server:
  port: 8888
# 使得/refresh不需要验权
management:
  security:
    enabled: false

# 访问时需要提供用户和密码
security:
  basic:
    enable: true
  # 这个接口不做用户名密码校验, /monitor接收git刷新通知
  ignored: /monitor
  user:
    name: ${CONFIG_SERVER_SECURITY_NAME:user}
    password: ${CONFIG_SERVER_SECURITY_PASSWORD:12345678}
encrypt:
  # 加解密用的秘钥
  key: ${CONFIG_SERVER_ENCRYPT_KEY:12345678}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://127.0.0.1:8761/eureka/}
  instance:
    preferIpAddress: true
    # 心跳间隔
    leaseRenewalIntervalInSeconds: 10

---
spring:
  profiles: prod
  # rabbitmq的地址 用户名 密码
  rabbitmq:
    host: ${PUBLIC_RABBITMQ_HOST:rabbitmq}
    username: ${PUBLIC_RABBITMQ_USERNAME:guest}
    password: ${PUBLIC_RABBITMQ_PASSWORD:guest}

server:
  port: 8888
# 使得/refresh不需要验权
management:
  security:
    enabled: false

# 访问时需要提供用户和密码
security:
  basic:
    enable: true
  # 这个接口不做用户名密码校验, /monitor接收git刷新通知
  ignored: /monitor
  user:
    name: ${CONFIG_SERVER_SECURITY_NAME:user}
    password: ${CONFIG_SERVER_SECURITY_PASSWORD:12345678}
encrypt:
  # 加解密用的秘钥
  key: ${CONFIG_SERVER_ENCRYPT_KEY:12345678}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://127.0.0.1:8761/eureka/}
  instance:
    preferIpAddress: true
    # 心跳间隔
    leaseRenewalIntervalInSeconds: 10