# 业务组件部署

version: "3.2"
services:
  # 1、订单服务
  zsc-service-one:
    # 镜像地址
    image: 123.207.79.123:5000/zsc-service-one:0.0.1-SNAPSHOT
    # 容器名称
    container_name: zsc-service-one
    ports:
      # 端口映射
      - "9005:9005"
    environment:
      # hostname URL
      - EUREKA_SERVICE_URL=http://zsc-eureka-1:8761/eureka/,http://zsc-eureka-2:8761/eureka/
      - HOSTNAME=zsc-service-one
      - LOGSTASH_HOST=logstash:4560
      - JAVA_OPTS=-Dspring.profiles.active=prod
    networks:
      # 加入集群网络
      - swarm_net
    volumes:
      # 将宿主机上的文件挂载到容器内
      - type: "bind"
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      # 实例数量
      replicas: 1
      # 更新选项
      update_config:
        # 每次更新多少个容器
        parallelism: 1
        # 间隔时间
        delay: 10s
      # 启动错误时，重新启动
      restart_policy:
        condition: on-failure
      resources:
        limits:
          # CPU限制
          cpus: '0.5'
          # 内存限制
          memory: 256M
    # 健康检查，启动后，当这个命令执行没问题，才会任何这个服务启动成功
    healthcheck:
      # 命令
      test: ["CMD", "curl", "-f", "http://localhost:9005/info"]
      # 间隔时间，安装应用的预计启动时间来设置。比如我们这个springcloud的应用，一般在1分钟半内预计启动完成
      interval: 1m30s
      timeout: 10s
      # 重试次数
      retries: 5
  
networks:
  swarm_net: